name: Deploy to Amazon S3

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy Website to S3 Bucket
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::118186523911:role/recordostyle-github-assume-role
        aws-region: us-east-2

    - run: aws s3 sync ./dist s3://recordostyle.com
      shell: bash